config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :flats do
    resources :viewings, only: [:new, :create]
  end

    # resources :viewings, only: [:show] do
    #   patch :accept
    #   patch :decline
    # end
  # Defines the root path route ("/")
  root to: 'pages#home'
  get '/requests' => 'pages#requests'
  resources :viewings, only: [:show, :index, :update, :edit, :destroy] do
    get :accept
    get :decline
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :viewings, dependent: :destroy
  geocoded_by :full_street_address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos
  CURRENCIES = ["€ - EUR", "£ - GBP", "$ - USD"]
  include PgSearch::Model
pg_search_scope :search_by_city,
  against: [ :title, :city, :description],
  using: {
    tsearch: { prefix: true }
  }

  def full_street_address
    address + " " + city
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  INTERESTS = ["Cooking", "Sports", "Party", "Training", "Outdoors"]
  # validates :first_name, presence: true, uniqueness: { scope: :last_name }
  # validates :last_name, presence: true
  # validates :interests, inclusion: { in: INTERESTS }

  has_many :viewings
  has_many :flats, dependent: :destroy
  has_one_attached :photo
end

app/models/viewing.rb
class Viewing < ApplicationRecord
  belongs_to :flat
  belongs_to :user

  include PgSearch::Model

  pg_search_scope :search_by_,
  against: [ :title, :city, :description],
  using: {
    tsearch: { prefix: true }
  }

  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :interests, :photo, :bio, :occupation, :city])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :interests])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    if params[:query].present?
      @flats = Flat.search_by_city(params[:query])
      @markers = @flats.geocoded.map do |flat|
        {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: 'info_window', locals: {flat: flat})
      }
      end
    else
      @flats = Flat.all
        @markers = @flats.geocoded.map do |flat|
          {
            lat: flat.latitude,
            lng: flat.longitude,
            info_window: render_to_string(partial: 'info_window', locals: {flat: flat})
          }
        end
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @owner = owner?(@flat)
    @currency = currency(@flat)
  end

  def new
    @flat = Flat.new
  end

  def create
    params = flat_params
    params[:user] = current_user
    @flat = Flat.new(params)
    @flat.save!
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:title, :description, :address, :rent, :user, :city, :available_from, :interests, :number_of_rooms, :currency, photos: [])
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def owner?(flat)
    if user_signed_in?
    current_user.id == flat.user_id
    end
  end

  def currency(flat)
    case flat.currency
    when "€ - EUR"
      "€"
    when "£ - GBP"
      "£"
    else
      "$"
    end
  end
  helper_method :currency
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @flats = Flat.last(6)
  end

  def requests
    @viewings = Viewing.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :photo)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/viewings_controller.rb
class ViewingsController < ApplicationController
  before_action :set_flat, only: %i[new create]

  def index
    @viewings = Viewing.all.order('date ASC')
  end

  def new
    @viewing = Viewing.new
  end

  def edit
    @viewing = Viewing.find(params[:id])
  end

  def update
    @viewing = Viewing.find(params[:id])
    @viewing.update(viewing_params)
    redirect_to viewings_path
  end

  def create
    @viewing = Viewing.new(viewing_params)
    @viewing.flat = @flat
    @viewing.user = current_user
    @viewing.save!
    redirect_to viewings_path
  end

  def destroy
    @viewing = Viewing.find(params[:id])
    @viewing.destroy
    redirect_to flat_path(@viewing.flat), status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end

  def viewing_params
    params.require(:viewing).permit(:date, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/_form.html.erb
<div style="width: 60%; margin: 20px auto;">
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :title %>
  <%= f.input :address %>
  <%= f.input :city %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.input :description %>
  <%= f.input :number_of_rooms %>
  <%= f.input :interests %>
  <%= f.input :currency, label: 'Rent Currency', collection: Flat::CURRENCIES %>
  <%= f.input :rent %>
  <%= f.input :available_from, :order => [:day, :month, :year] %>
  <div style="text-align: center;">
  <%= f.submit class: "btn-flat" %>
  </div>
<% end %>
</div>

app/views/flats/_info_window.html.erb
<div style="text-align: left;">
  <h3 style="font-size: 20px;"><%= flat.title %></h3>
  <p style="margin: 0px;"><%=flat.address%>, <%= flat.city %>
  <p style="margin: 0px;">Available from <%= flat.available_from.strftime("%A, %d %B %Y") %> </p>
  <p style="margin: 0px;">Rent: <%= flat.rent %> <%= flat.currency %> </p>
</div>

app/views/flats/edit.html.erb
<h1 style="text-align:center;">Update your Ad</h1>

<div class="container">
<%= render "form", flat: @flat %>
</div>

app/views/flats/index.html.erb
<div style="text-align: center;" class="content, container";>
  <h1>Discover our flats</h1>
</div>


<div class="flat-index-content">
  <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Next destination is ..."
    %>
    <%= submit_tag "Search", class: "btn-search ms-2" %>
  <% end %>
</div>

<div style=" height: 300px; padding: 30px auto; margin: 0px auto;",
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="flat-index-content">
    <% @flats.each do |flat| %>
      <%= link_to flat_path(flat) do  %>
        <div class="flat-card-index">
          <% if flat.photos.attached? %>
            <%= cl_image_tag flat.photos.first.key, height: 200, width: 300, crop: :fill, class: 'image-flat-cover',  alt: "picture of flat" %>
          <% else %>
            <%= image_tag 'flat-placeholder.jpg', class: 'image-flat-cover',  alt: "image placeholder for flat" %>
          <% end %>
          <div class="flat-card-content">
            <p><%= flat.title %></p>
            <p><%= currency(flat) %><%= flat.rent %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/flats/new.html.erb
<h1 style="text-align:center;">Post Ad</h1>

<div class="container">
<%= render "form", flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="container show-flat-content" style="width: 70%">
  <h1 style="padding: 10px 0px; text-align: center"><%= "Welcome to #{@flat.title}!" %></h1>

<% if @owner %>
  <div style="text-align: center; padding: 20px;">
    <%= link_to "Update Ad", edit_flat_path, class: 'secondary-btn' %>
    <%= link_to "Delete Ad",
    flat_path(@flat), class: 'secondary-btn',
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %>
  </div>
<% end %>




<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">

      <% @flat.photos.each_with_index do |photo, index| %>
        <div class="carousel-item <%= index == 0 ? 'active' : '' %>">
          <%= cl_image_tag photo.key, crop: :fill, class: 'd-block w-100',  alt: "picture of flat" %>
        </div>
      <% end %>

  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>



  <div class="flat-content">
    <p><%= @flat.description%> </p>
    <p><span class="strong">Address: </span> <%= @flat.address %> (<%= @flat.city %>)</p>
    <p><span class="strong">Number of rooms: </span> <%= @flat.number_of_rooms %> </p>
    <p><span class="strong">Rent:</span> <%= @currency %><%= @flat.rent %></p>
    <p><span class="strong">Available from</span> <%= @flat.available_from.strftime("%A, %d %B %Y") %> </p>
  </div>

<% if !@owner && user_signed_in? %>
  <div style="text-align: center; padding: 20px;">
    <%= link_to "Book a viewing", new_flat_viewing_path(@flat), class: 'btn-flat' %>
  </div>

<% elsif !@owner %>
<div style="text-align: center; padding: 40px;">
  Sign up for free or login to book a viewing
  <div style= "padding: 20px;">
    <%= link_to "Sign up for Free", new_user_registration_path, class: "btn-flat" %>
    <%= link_to "Login", user_session_path, class: 'btn-flat' %>
    </div>
    <div style= "padding: 20px; ">
    <%= link_to 'Get back to flats', flats_path, class: 'secondary-btn'%>
  </div>
  </div>
<% end %>

<% if user_signed_in? %>
  <div class="owner-details card-owner">
 <% if @flat.user.photo.attached? %>
                  <%= cl_image_tag @flat.user.photo.key, class:"avatar-lg", width: 50, gravity: "auto", radius: "max" %>
                <% else %>
                  <%= image_tag 'user-placeholder.png', width: 50, class: "avatar-lg", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>
                    <div class="card-owner-infos">
    <h2>This property is owned by <%= @flat.user.first_name %> <%= @flat.user.last_name %></h2>
    <p><%= @flat.user.first_name %> lives in <%= @flat.city%>. </p>
     <p> <%= @flat.user.first_name %> enjoys <%= @flat.user.interests%>, and their flatmates enjoy <%= @flat.interests %>  </p>
    </div>


  </div>




  <div style="text-align: center; padding: 40px;">
  <p>Not what you were looking for?</p>
    <%= link_to 'Get back to flats', flats_path, class: 'secondary-btn' %>
  </div>

  <% end %>

</div>

app/views/flats/update.html.erb
<h1>Hello from the View "Update" HTML</h1>

<div>
<%= render "form", flat: @flat %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rooms For Timoty</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" %>


    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>


  </head>

  <body class="bg-light", style="min-height: 100vh; display: flex;
  flex-direction: column; text-decoration: none;">


   <%= render 'shared/navbar' %>

 <%= render "shared/flashes" %>

  <div class="container" style="padding: 20px 0px";>
    <%= yield %>
  </div>

<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Rooms for Timoty is made with <i class="fas fa-heart"></i> by <a href="https://github.com/asaleh96/">Ahmed</a>,
    <a href="https://github.com/bizipoz/">Caroline</a>, <a href="https://github.com/SIFAR101">Shahid</a> and <a href="https://github.com/simonabar1/">Simona</a>.
  </div>
</div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="text-align: center; background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1481277542470-605612bd2d61?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1106&q=80);">
  <div class="container">
    <h1>Find a new home with Timoty</h1>
    <%= link_to  "Find a Flat", flats_path, class: 'btn-flat' %>
  </div>
</div>

<div class="container" style="padding-top: 40px; padding-bottom: 40px;">
<h2 style="text-align: center;"> What's new? </h2>
  <div class="flat-index-content">
    <% @flats.each do |flat| %>
      <%= link_to flat_path(flat) do  %>
        <div class="flat-card-index">
          <% if flat.photos.attached? %>
            <%= cl_image_tag flat.photos.first.key, height: 200, width: 300, crop: :fill %>
          <% else %>
            <%= image_tag 'flat-placeholder.jpg', class: 'image-flat-cover',  alt: "image placeholder for flat" %>
          <% end %>
          <div class="flat-card-content">
            <p><%= flat.title %></p>
            <p><%= flat.currency.nil? ? flat.currency : flat.currency[0] %><%= flat.rent %></p>

          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  </div>

app/views/pages/requests.html.erb
<div class="container show-flat-content" style="width: 70%">
<div id='My_flats' class="tabcontent">
    <h2 style="text-align: center; padding: 20px;"> My Requests </h2>


    <% @viewings.each do |viewing| %>
      <% if current_user == viewing.flat.user %>

          <div class="notification">

            <div style="width: 10%; text-align: center;">
                <% if viewing.user.photo.attached? %>
                <%= link_to user_path(viewing.user) do %>
                  <%= cl_image_tag viewing.user.photo.key, class:"avatar-lg", width: 50, gravity: "auto", radius: "max" %>
                <% end %>
                <% else %>
                <%= link_to user_path(viewing.user) do %>
                  <%= image_tag 'user-placeholder', width: 50, class: "avatar-lg" %>
                <% end %>
                <% end %>

            </div>

            <div class="notification-content" style='width: 60%'>
                <p style="font-weight: bold;"> <small> <%= viewing.date.strftime("%A, %d %B %Y at %H:%M") %> </small></p>
                <p> <span style="font-weight:bold;"><%= viewing.user.first_name %></span>   would like to see <span style="font-weight:bold;">  <%= link_to viewing.flat.title, flat_path(viewing.flat), style: 'text-decoration: none; color: black;'%> </span>. </p>
                <p>"<%= viewing.message %>"</p>
            </div>

            <div style="width: 30%">
                <% if viewing.status == "pending" %>
                  <%= link_to 'Accept', viewing_accept_path(viewing), class: 'accept-btn' %>
                  <%= link_to 'Decline', viewing_decline_path(viewing), class: 'decline-btn'  %>


                <% elsif viewing.status == "accepted" %>
                  <div style="text-align: center;", class="">
                    <p><i class="fa-solid fa-circle-check"></i> </p>
                    <p class="" style= "text-align: center;"> <%= "Confirmed" %></p>
                  </div>


                <% elsif viewing.status == "rejected" %>
                  <div style="text-align: center;", class="">
                    <p><i class="fa-solid fa-circle-xmark"></i></p>
                    <p><%=  "Declined" %></p>
                  </div>

                <% else %>
                  <div style="text-align: center;", class="">
                    <p><i class="fa-solid fa-circle-question"></i>"></i></p>
                    <p><%=  "Pending" %></p>
                  </div>
                <% end %>

              </div>

        </div>

      <% end %>
    <% end %>
  </div>
    <div style="text-align: center; padding: 20px;">
    <%= link_to 'Get back to flats', flats_path, class: 'secondary-btn' %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'temporary-logo.png', alt: 'Application Logo', class: 'avatar' %>
      <span class="logo-title"> <%= "Rooms for Timoty"%></span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Viewings", viewings_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "My Requests", requests_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Post an Ad", new_flat_path, class: "nav-link" %>
          </li>

          <li class='nav-item'>
           <div class="nav-item dropdown show">
              <a class="" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.photo.attached? %>
                  <%= cl_image_tag current_user.photo.key, class: 'avatar', gravity: "auto", radius: "max" %>
                <% else %>
                  <%= image_tag 'user-placeholder.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="#"><%= link_to "My Profile", user_path(current_user), class: "nav-link" %></a>
              <a class="dropdown-item" href="#"><%= link_to "Edit Profile", edit_user_path(current_user), class: "nav-link" %></a>
              <a class="dropdown-item" href="#"><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %></a>
            </div>
          </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div style="width: 60%; margin: 20px auto;">
<%= simple_form_for(@user) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :city %>
  <%= f.input :occupation %>
  <%= f.input :bio, label: 'Profile', as: :text, :input_html => { :cols => 5, :rows => 5 }, placeholder: 'Tell more about yourself..' %>
  <%= f.input :interests %>
  <%= f.input :photo %>

  <div style="text-align: center;">
  <%= f.submit class: "btn-flat" %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1 style="text-align:center;">Update User</h1>

<div class="container">
<%= render "form", user: @user %>
</div>

app/views/users/show.html.erb
<div class="container" style="width: 60%; margin: 20px auto;" >


    <div class="container">
    <div class="first-card">
    <h1 class="profile-h1"> Hello, I'm <%= @user.first_name%>!</h1>
       <% if @user.photo.attached? %>
                  <%= cl_image_tag @user.photo.key, class: 'rounded-circle', style: 'width: 150px', gravity: "auto", radius: "max" %>
                <% else %>
                  <%= image_tag 'user-placeholder.png', class: 'rounded-circle', style: 'width: 150px', id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <% end %>
                <ul class="profile-ul">
          <li class="subtitle profile-li"> <i class="subtitle-symbol fa-sharp fa-solid fa-briefcase"></i> <%= @user.occupation %></li>
          <li class="subtitle profile-li"><i class="subtitle-symbol fa-solid fa-location-dot"></i> <%= @user.city %></li>
        </h2>
        <p> <%= @user.bio %> </p>
      </ul>





  </div>
  </div>

<div style="text-align: center; padding: 20px;">
    <%= link_to 'Back to Flats', flats_path, class: 'secondary-btn' %>
    <%= link_to 'Back to Viewings', viewings_path, class: 'secondary-btn' %>
  </div>

</div>

app/views/viewings/_form.html.erb
<div style="width: 60%; margin: 20px auto;">
    <div style="padding: 20px 0;">
      <%= simple_form_for [@flat, @viewing] do |f| %>
        <%= f.input :date, :order => [:day, :month, :year] %>
        <%= f.input :message %>
          <div style="text-align: center;">
            <%= f.submit "Submit", class: 'btn-flat' %>
          </div>
      <% end %>
    </div>
</div>

app/views/viewings/_viewing_status.html.erb
<% if @viewing.status = 0 %>
  <%= link_to 'Accept', viewing_accept_path(viewing.id), class: 'secondary-btn' %>
  <%= link_to 'Reject', viewing_decline_path(viewing.id), class: 'secondary-btn' %>
<% elsif @viewing.status = 1 %>
<%= "This viewing has been accepted" %>
<% else %>
<%=  "This viewing has been rejected" %>
<% end %>

<%#
# WHen status = 0 (pending)
 > we want the 2 buttons for accept or Reject
# When Status = 1 (accepted)
 > We want to see > Green border the for the viewing + "This viewing has been accepted"
# When status = 2 (rejected)
 > We want to see > Red border the for the viewing + "This viewing has been rejected" %>

app/views/viewings/edit.html.erb
<h1 style="text-align:center;">Update Viewing</h1>

<div class="container">
<%= render "form", viewing: @viewing %>
</div>

app/views/viewings/index.html.erb
<div class="container" style="width: 70%" >

      <%# <div class="flat-index-content">
        <%= form_with url: viewings_path, method: :get, class: "d-flex" do %>
          <%# <%=text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "e.g. 65 rue de Groussay"
          %>
          <%# <%= submit_tag "Search", class: "btn btn-flat" %>
        <%# <% end %>
      <%# </div>  %>


  <h2 style="text-align: center; padding: 30px 0 30px 0;"> My Viewings </h2>
  <% @viewings.each do |viewing| %>
      <% if current_user == viewing.user %>
        <%= link_to flat_path(viewing.flat), class: "flat-link" do  %>

          <div class="notification">
              <div style="width: 20%; text-align: center;">
                <%= image_tag 'flat-placeholder.jpg', class: 'rounded-3', style: 'width: 150px;',  alt: "image placeholder for flat" %>
              </div>


              <div class="notification-content">

                  <p style="font-weight: bold;"> <small> <%= viewing.date.strftime("%A, %d %B %Y at %H:%M") %> </small></p>
                  <p> Your requested a viewing for <span style="font-weight:bold;"><%= viewing.flat.title %> </span> </p>
                  <p><%= viewing.flat.address %>, <%= viewing.flat.city %></p>
                  <br>



                  <% if viewing.status == "accepted" %>
                    <p style="font-weight: bold;"> 🥳 Your viewing request has been accepted. </p>
                  <% elsif viewing.status == "rejected" %>
                   <p style="font-weight: bold;"> 😪 Your viewing request has been rejected. <p>
                  <% else %>
                 <p style="font-weight: bold;">  ⏳ This viewing request is pending! <p>
                  <% end %>
                   <% end %>
        </div>
        <div style="width: 20%";>
          <%= link_to 'Edit',  edit_viewing_path(viewing), class: 'secondary-btn'%>
        </div>
        </div>

      <% end %>
    <% end %>
</div>

  <div style="text-align: center; padding: 20px;">
    <%= link_to 'Get back to flats', flats_path, class: 'secondary-btn' %>
  </div>

</div>

app/views/viewings/new.html.erb
<div class="container">


    <h1 style="text-align: center">Book a Viewing for <%= @flat.title %> </h1>
  <%= render "form", viewing: @viewing %>
  </div>

app/views/viewings/show.html.erb
<div class="container show-flat-content">
  <h1 style="padding: 10px 0px; text-align: center"><%= "You have a Viewing on #{viewing.date}!" %></h1>
  <p><%="See " %></p>
</div>